version: '3'

services:
  builder:
    image: lu1as/hcloud
    environment:
      ANSIBLE_HOST_KEY_CHECKING: "False"
      HCLOUD_VM_NAME: iconnect-kernel-compile
      HCLOUD_VM_TYPE: ccx31
      HCLOUD_VM_LOCATION: nbg1
      HCLOUD_VM_SSH_KEY_NAME: gitlab-ci
      HCLOUD_VM_IMAGE: debian-10
      HCLOUD_CACHE_VOLUME_NAME: iconnect-kernel-cache
      HCLOUD_TOKEN: $HCLOUD_TOKEN
      HCLOUD_CACHE_VOLUME_ID: $HCLOUD_CACHE_VOLUME_ID
      CI_REPOSITORY_URL: https://git.zotha.de/lukas/iconnect-debian
      CI_COMMIT_REF_NAME: master
    volumes:
      - $PWD:/home/user/iconnect-debian
    command: sleep 36000
