- name: build kernel packages
  hosts: cloud_server
  vars:
    kernel_version: "{{ lookup('file', '../.ci_kernel_version') }}"
    kernel_deb_version: "{{ lookup('pipe', 'date +%d%m%y') }}"
  tasks:
    - debug:
        msg: "building image and packages with kernel {{ kernel_version }}"

    - name: install requirements
      apt:
        name:
          - git
          - git-lfs
          - rsync
          - build-essential
          - crossbuild-essential-armel
          - u-boot-tools
          - wget
          - patch
          - util-linux
          - dosfstools
          - lzma
          - debootstrap
          - qemu-user-static
          - binfmt-support
          - bc
          - libssl-dev
          - fakeroot
          - dpkg-dev
          - flex
          - bison
          - cpio
          - kmod
        update_cache: true

    - name: checkout repo
      git:
        repo: "{{ lookup('env','CI_REPOSITORY_URL') }}"
        dest: /root/iconnect-debian
        version: "{{ lookup('env','CI_COMMIT_REF_NAME') }}"
 
    - name: create work directory
      file:
        path: /root/iconnect-debian/work
        state: directory

    - name: mount cache volume
      mount:
        path: /root/iconnect-debian/work
        src: "/dev/disk/by-id/{{ lookup('env','HCLOUD_CACHE_VOLUME_ID') }}"
        fstype: ext4
        opts: discard,defaults
        state: mounted

    - name: create config.vars
      template:
        src: ./config.vars.sample
        dest: /root/iconnect-debian/config.vars

    - name: clear filesystem cache
      file:
        path: /root/iconnect-debian/work/image/fs-system
        state: absent
      when: lookup('env','CLEAR_FILESYSTEM_CACHE') == 'true'

    - name: clear kernel cache
      file:
        path: /root/iconnect-debian/work/kernel
        state: absent
      when: lookup('env','CLEAR_KERNEL_CACHE') == 'true'

    - name: run job
      shell: CI='true' ./run.sh image
      args:
        chdir: /root/iconnect-debian
        executable: /bin/bash
      async: 3600
      poll: 10

    - name: pull kernel packages
      synchronize:
        mode: pull
        src: "/root/iconnect-debian/work/kernel/{{item}}"
        dest: "{{ lookup('env','CI_PROJECT_DIR') }}/kernel-pkgs"
      loop:
        - "linux-headers-{{ kernel_version }}-iconnect_{{ kernel_deb_version }}_armel.deb"
        - "linux-image-{{ kernel_version }}-iconnect_{{ kernel_deb_version }}_armel.deb"
        - "linux-libc-dev_{{ kernel_deb_version }}_armel.deb"

    - name: pull image
      synchronize:
        mode: pull
        src: "/root/iconnect-debian/work/iconnect-stick-{{ kernel_version }}.raw"
        dest: "{{ lookup('env','CI_PROJECT_DIR') }}"

    - name: umount cache volume
      mount:
        path: /root/iconnect-debian/work
        state: unmounted
