# initialization
- name: prepare cloud server
  hosts: localhost
  tasks:
    - name: discover cloud server
      shell: |
        hcloud server describe {{ lookup('env','HCLOUD_VM_NAME') }}
      register: cloud_server

    - name: add cloud server to hosts
      add_host:
        name: cloud_server
        ansible_host: "{{ cloud_server.stdout | regex_search('(?:[0-9]{1,3}\\.){3}[0-9]{1,3}') }}"
        ansible_user: root

    - name: create local artifact directory
      file:
        path: ../kernel-pkgs
        state: directory

    - name: wait for cloud server
      wait_for:
        host: cloud_server
        timeout: 60
        sleep: 5

# build packages
- import_playbook: build.yml
